### ISSUE TITLE
Tailwind Config file/PostCSS - declaration file

### ISSUE THREAD

**Issue by ronaldocostaj** [georgwittberger/salesforce-community-tailwindcss#1]
Hello Sir, first of all, thank you so much for this immense contribution!
I would like to use TailWindUI in one of my Community projects.
It would be immensely helpful to leverage TailwindUI and TailwindCSS.

Can you kindly help with the below? Many of the Tailwind examples leverages their plugins, and currently I'm facing the error below.

```
Could not find a declaration file for module '@tailwindcss/forms'. '/Users/roncostaj/Desktop/SAASTEPS/Code/demo-org/demo-org/node_modules/@tailwindcss/forms/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/tailwindcss__forms` if it exists or add a new declaration (.d.ts) file containing `declare module '@tailwindcss/forms';`ts(7016)
```

Error when running those lines: `declare: not valid in this context: @tailwindcss/forms
module=''`

I'm also facing the same error for your postcss.config.js file on the cssnano row.

`Could not find a declaration file for module 'cssnano'.`

Can you kindly help?
Thank you,
Ron Costa

**Comment by georgwittberger** [comment]
Sounds a bit strange because this looks like a TypeScript error but there I didn't use TypeScript in my project. Do you have a `tsconfig.json` in your project?

One solution could be adding a declaration file manually, see this post: https://github.com/tailwindlabs/tailwindcss-forms/issues/18#issuecomment-735448249

Regarding CSSNano error: Install declarations first: `npm install --save-dev @types/cssnano` or `yarn add --dev @types/cssnano` - if this does not help take same approach as with TailwindCSS Forms module.

Good luck. :-)
